return {
    -- "zbirenbaum/copilot.lua",
    -- config = function()
    --     require("copilot").setup(
    --         {
    --             suggestion = {
    --                 enabled = true,
    --                 auto_trigger = true,
    --                 hide_during_completion = false,
    --                 debounce = 75,
    --                 keymap = {
    --                     accept = "<C-o>",
    --                     accept_word = "<C-w>",
    --                     accept_line = "<C-l>",
    --                     next = "<M-]>",
    --                     prev = "<M-[>",
    --                     dismiss = "<C-]>",
    --                 },
    --             }
    --         }
    --     )
    --
    --     vim.keymap.set("n", "<leader>ce", "<CMD>Copilot<CR>", { silent = true })
    --     vim.keymap.set("n", "<leader>cd", ":Copilot detach<CR>")
    -- end,
}
