#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off 
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0
# yabai -m config active_window_opacity        1
# yabai -m config normal_window_opacity        1
yabai -m config window_border_width          0
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# animations settings
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_frame_rate  0.0

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   10

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main: 100:0

# apps to not manage (ignore)
# yabai -m rule --add app="^Finder" manage=off sticky=on layer=above 
yabai -m rule --add app="^System Preferences" manage=off
# yabai -m rule --add app="^Mail" manage=off
yabai -m rule --add app="^RayCast" manage=off

# sketchybar stuff
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
echo "yabai configuration loaded.."
