require("core.plugin_config.catpuccin")
require("core.plugin_config.telescope")
require("core.plugin_config.harpoon")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp")
require("core.plugin_config.comment")
require("core.plugin_config.luasnip")
require("core.plugin_config.actions")
require("core.plugin_config.vimtex")
require("core.plugin_config.zenmode")
require("core.plugin_config.typst")
require("core.plugin_config.formatter")
-- require("core.plugin_config.copilot")
