#!/usr/bin/env bash
set -euo pipefail

output_file="${1:-$HOME/.config/Brewfile.mac-mini.daily-driver}"

default_excluded_casks=(
  brave-browser
  google-chrome
  docker-desktop
)

default_excluded_formulas=()

excluded_casks=("${default_excluded_casks[@]}")
excluded_formulas=()

if [[ -n "${MIRROR_EXCLUDE_CASKS:-}" ]]; then
  for item in ${MIRROR_EXCLUDE_CASKS//,/ }; do
    [[ -n "$item" ]] && excluded_casks+=("$item")
  done
fi

if [[ -n "${MIRROR_EXCLUDE_FORMULAS:-}" ]]; then
  for item in ${MIRROR_EXCLUDE_FORMULAS//,/ }; do
    [[ -n "$item" ]] && excluded_formulas+=("$item")
  done
fi

contains() {
  local needle="$1"
  shift
  local item

  for item in "$@"; do
    [[ "$item" == "$needle" ]] && return 0
  done

  return 1
}

filtered_formulas=()
tap_list=()
while IFS= read -r formula; do
  if (( ${#excluded_formulas[@]} > 0 )); then
    contains "$formula" "${excluded_formulas[@]}" && continue
  fi
  filtered_formulas+=("$formula")

  if [[ "$formula" == */*/* ]]; then
    tap_list+=("${formula%/*}")
  fi
done < <(brew leaves | sort)

filtered_casks=()
while IFS= read -r cask; do
  if (( ${#excluded_casks[@]} > 0 )); then
    contains "$cask" "${excluded_casks[@]}" && continue
  fi
  filtered_casks+=("$cask")
done < <(brew list --cask | sort)

if contains "aerospace" "${filtered_casks[@]}"; then
  tap_list+=("nikitabobko/tap")
fi

if contains "dorion" "${filtered_casks[@]}"; then
  tap_list+=("psharma04/dorion")
fi

mkdir -p "$(dirname "$output_file")"

{
  printf '# Generated by %s on %s\n' "$(basename "$0")" "$(date '+%Y-%m-%d %H:%M:%S %Z')"
  printf '# Source host: %s\n' "$(hostname -s)"
  printf '# Intentionally excluded casks: %s\n' "${default_excluded_casks[*]}"
  printf '\n'

  while IFS= read -r tap; do
    [[ -z "$tap" ]] && continue
    printf 'tap "%s"\n' "$tap"
  done < <(printf '%s\n' "${tap_list[@]}" | sort -u)

  printf '\n'

  for formula in "${filtered_formulas[@]}"; do
    printf 'brew "%s"\n' "$formula"
  done

  printf '\n'

  for cask in "${filtered_casks[@]}"; do
    if [[ "$cask" == "aerospace" ]]; then
      printf 'cask "%s"\n' "nikitabobko/tap/aerospace"
    elif [[ "$cask" == "dorion" ]]; then
      printf 'cask "%s"\n' "psharma04/dorion/dorion"
    else
      printf 'cask "%s"\n' "$cask"
    fi
  done
} > "$output_file"

printf 'Wrote %s\n' "$output_file"
